which product category drive or drag profitability

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv(r"C:\Users\Talib\Desktop\DA - Projects\New Project Resume\Dataset\files v2\Cleaned Data\Fact_Sales.csv")
df

,Row_ID,Order_ID,Date_ID,Order_Date,Ship_Date,Delivery_Duration(Days),Ship_Mode,Customer_ID,Product_ID,Quantity,Unit_Price_BDT,Discount_Pct,Sales_BDT,Cost_BDT,Profit_BDT,Profit_Margin_Pct,Payment_Method,Is_Returned
0,1,ORD-105638,DATE-20230101,01-01-23,02-01-23,1,Standard,CUS-02321,PROD-00001,8,4771.66,0.042,36570.00,34620.64,1949.36,5.33,Cash on Delivery,False
1,2,ORD-102334,DATE-20230101,01-01-23,02-01-23,1,Standard,CUS-01456,PROD-00002,3,11470.75,0.100,30971.03,22946.73,8024.30,25.91,bKash,True
2,3,ORD-100570,DATE-20230101,01-01-23,08-01-23,7,Standard,CUS-00028,PROD-00003,11,58.85,0.077,597.50,548.44,49.06,8.21,Cash on Delivery,False
3,4,ORD-101183,DATE-20230101,01-01-23,02-01-23,1,Standard,CUS-00412,PROD-00004,4,11474.86,0.099,41355.40,38073.88,3281.52,7.93,bKash,False
4,5,ORD-104389,DATE-20230101,01-01-23,03-01-23,2,Standard,CUS-01955,PROD-00005,4,1722.10,0.196,5538.27,5080.03,458.24,8.27,Cash on Delivery,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9085,9086,ORD-103318,DATE-20251230,30-12-25,04-01-26,5,Standard,CUS-00533,PROD-07713,3,49009.23,0.052,139382.25,134636.13,4746.12,3.41,Cash on Delivery,False
9086,9087,ORD-108236,DATE-20251231,31-12-25,02-01-26,2,Same-Day,CUS-00895,PROD-01022,1,4270.98,0.213,3361.26,2882.84,478.42,14.23,bKash,False
9087,9088,ORD-106406,DATE-20251231,31-12-25,05-01-26,5,Standard,CUS-01913,PROD-02484,3,43433.88,0.051,123656.26,119053.06,4603.20,3.72,Cash on Delivery,False
9088,9089,ORD-103140,DATE-20251231,31-12-25,02-01-26,2,Standard,CUS-01687,PROD-07714,11,644.09,0.596,2862.34,-297.56,3159.90,110.40,Credit/Debit Card,False
9089,9090,ORD-108240,DATE-20251231,31-12-25,05-01-26,5,Standard,CUS-01045,PROD-07480,2,5692.56,0.070,10588.16,7551.98,3036.18,28.68,Credit/Debit Card,True

In [3]:
product = pd.read_csv(r"C:\Users\Talib\Desktop\DA - Projects\New Project Resume\Dataset\files v2\Cleaned Data\Dim_Product.csv")
product

,Product_ID,Category,Sub_Category,Product_Name
0,PROD-00001,Electronics,Smartphone,Smartphone Model-491
1,PROD-00002,Home_Living,Furniture,Furniture Model-360
2,PROD-00003,Grocery_FMCG,Beverages,Beverages Model-461
3,PROD-00004,Home_Living,Bedding,Bedding Model-774
4,PROD-00005,Garments,Kids Wear,Kids Wear Model-303
...,...,...,...,...
7709,PROD-07710,Beauty_Health,Makeup,Makeup Model-747
7710,PROD-07711,Electronics,Headphone,Headphone Model-858
7711,PROD-07712,Grocery_FMCG,Cleaning Supplies,Cleaning Supplies Model-994
7712,PROD-07713,Electronics,Laptop,Laptop Model-966
7713,PROD-07714,Garments,Kids Wear,Kids Wear Model-170

In [5]:
df_product = df.merge(
    product[['Product_ID', 'Category', 'Sub_Category', 'Product_Name']],
    on='Product_ID',
    how='left'
)

print(df_product.columns)

Index(['Row_ID', 'Order_ID', 'Date_ID', 'Order_Date', 'Ship_Date',
       'Delivery_Duration(Days)', 'Ship_Mode', 'Customer_ID', 'Product_ID',
       'Quantity', 'Unit_Price_BDT', 'Discount_Pct', 'Sales_BDT', 'Cost_BDT',
       'Profit_BDT', 'Profit_Margin_Pct', 'Payment_Method', 'Is_Returned',
       'Category', 'Sub_Category', 'Product_Name'],
      dtype='str')

In [6]:
category_analysis = (
    df_product.groupby('Category')
    .agg(
        Revenue=('Sales_BDT', 'sum'),
        Cost=('Cost_BDT', 'sum'),
        Profit=('Profit_BDT', 'sum'),
        Quantity=('Quantity', 'sum')
    )
    .reset_index()
)

category_analysis['Margin_Pct'] = (
    category_analysis['Profit'] /
    category_analysis['Revenue'] * 100
)

category_analysis['Revenue_Share_Pct'] = (
    category_analysis['Revenue'] /
    category_analysis['Revenue'].sum() * 100
)

category_analysis['Profit_Share_Pct'] = (
    category_analysis['Profit'] /
    category_analysis['Profit'].sum() * 100
)

print("CATEGORY PROFITABILITY")
print(
    category_analysis
    .sort_values('Profit', ascending=False)
    .round(2)
)

CATEGORY PROFITABILITY
           Category       Revenue          Cost       Profit  Quantity  \
2       Electronics  1.944951e+08  1.801573e+08  14337805.16      6507
4          Garments  2.204429e+07  1.778340e+07   4260883.78     10784
6       Home_Living  2.800449e+07  2.493840e+07   3097596.52      4114
3          Footwear  1.019176e+07  8.749319e+06   1442441.25      3885
0     Beauty_Health  7.978225e+06  6.635903e+06   1342322.37      4823
5      Grocery_FMCG  1.038494e+07  9.479113e+06    905825.52     18371
1  Books_Stationery  3.132042e+06  2.792485e+06    339557.17      3720

   Margin_Pct  Revenue_Share_Pct  Profit_Share_Pct
2        7.37              70.41             55.73
4       19.33               7.98             16.56
6       11.06              10.14             12.04
3       14.15               3.69              5.61
0       16.82               2.89              5.22
5        8.72               3.76              3.52
1       10.84               1.13              1.32

Profit Drive

In [7]:
print("\nTOP PROFIT DRIVING CATEGORIES")

print(
    category_analysis
    .sort_values('Profit', ascending=False)
    .head(5)
    [['Category', 'Revenue', 'Profit', 'Margin_Pct']]
    .round(2)
)

TOP PROFIT DRIVING CATEGORIES
        Category       Revenue       Profit  Margin_Pct
2    Electronics  1.944951e+08  14337805.16        7.37
4       Garments  2.204429e+07   4260883.78       19.33
6    Home_Living  2.800449e+07   3097596.52       11.06
3       Footwear  1.019176e+07   1442441.25       14.15
0  Beauty_Health  7.978225e+06   1342322.37       16.82

Profit Drag

In [8]:
print("\nLOWEST MARGIN CATEGORIES")

print(
    category_analysis
    .sort_values('Margin_Pct')
    .head(5)
    [['Category', 'Revenue', 'Profit', 'Margin_Pct']]
    .round(2)
)

LOWEST MARGIN CATEGORIES
           Category       Revenue       Profit  Margin_Pct
2       Electronics  1.944951e+08  14337805.16        7.37
5      Grocery_FMCG  1.038494e+07    905825.52        8.72
1  Books_Stationery  3.132042e+06    339557.17       10.84
6       Home_Living  2.800449e+07   3097596.52       11.06
3          Footwear  1.019176e+07   1442441.25       14.15

negative profit

In [9]:
print("\nLOSS-MAKING CATEGORIES")

print(
    category_analysis[
        category_analysis['Profit'] < 0
    ]
    [['Category', 'Revenue', 'Profit', 'Margin_Pct']]
    .sort_values('Profit')
    .round(2)
)

LOSS-MAKING CATEGORIES
Empty DataFrame
Columns: [Category, Revenue, Profit, Margin_Pct]
Index: []